version: "3.9"

services:
  boot-node:
    image: hyperledger/besu:latest
    container_name: "credaegis-boot-node"
    networks:
      besu-net:
        ipv4_address: 172.25.0.2
    ports:
      - "8000:8000"
      - "30300:30300/tcp"
      - "30300:30300/udp"
    volumes:
      - ./boot-node:/usr/app/
    command: --config-file=/usr/app/config.toml

  node-1:
    image: hyperledger/besu:latest
    container_name: "credaegis-node-1"
    networks:
      besu-net:
        ipv4_address: 172.25.0.3
    ports:
      - "8001:8001"
      - "30301:30301/tcp"
      - "30301:30301/udp"
    volumes:
      - ./node-1:/usr/app/
    command: ["--config-file=/usr/app/config.toml",
              "--bootnodes=enode://11179afc047904102c1bf80ab648e2a3a0d7f794288e88796c4cc323fbd687111faa2f37da65d7ffd7f9ccf8a437eb8bdba84a4ac1970eeeb3c6bbb96032de9b@172.25.0.2:30300"]

  node-2:
    image: hyperledger/besu:latest
    container_name: "credaegis-node-2"
    networks:
      besu-net:
        ipv4_address: 172.25.0.4
    ports:
      - "8002:8002"
      - "30302:30302/tcp"
      - "30302:30302/udp"
    volumes:
      - ./node-2:/usr/app/
    command: ["--config-file=/usr/app/config.toml",
              "--bootnodes=enode://11179afc047904102c1bf80ab648e2a3a0d7f794288e88796c4cc323fbd687111faa2f37da65d7ffd7f9ccf8a437eb8bdba84a4ac1970eeeb3c6bbb96032de9b@172.25.0.2:30300"]


  node-3:
    image: hyperledger/besu:latest
    container_name: "credaegis-node-3"
    networks:
      besu-net:
        ipv4_address: 172.25.0.5
    ports:
      - "8003:8003"
      - "30303:30303/tcp"
      - "30303:30303/udp"
    volumes:
      - ./node-3:/usr/app/
    command: ["--config-file=/usr/app/config.toml",
              "--bootnodes=enode://11179afc047904102c1bf80ab648e2a3a0d7f794288e88796c4cc323fbd687111faa2f37da65d7ffd7f9ccf8a437eb8bdba84a4ac1970eeeb3c6bbb96032de9b@172.25.0.2:30300"]


networks:
  besu-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: "172.25.0.0/16"
          gateway: "172.25.0.1"
      